### ISSUE TITLE
https://charlottemach.com offline ?

### ISSUE THREAD

**Issue by lwitzani** [charlottemach/mhz14a-sensor#1]
Hello,

this is is not a real issue with the repository. 

Some time ago i bookmarked the page https://charlottemach.com/2020/05/17/co2-sensor-raspi.html and ordered the sensor. 
The sensor came in the mail today and i wanted to look at the website again but it is offline with 404. Do you know something about this?
Do you have the info somewhere else :) ? 

Thanks so much!

**Comment by charlottemach** [comment]
Thanks for the info! I renamed the master branch to main a while back, and apparently that broke github pages. Should be working again.
Alternatively you can always find the source here: https://github.com/charlottemach/charlottemach.github.io/blob/main/_posts/2020-05-17-co2-sensor-raspi.html

**Comment by lwitzani** [comment]
Perfect! Thank you 😊!!
