### ISSUE TITLE
Can I use this?

### ISSUE THREAD

**Issue by ashleyoldershaw** [charlottemach/mhz14a-sensor#2]
Hi Charlotte!

Just wanted to say your code and guide here was useful for me - I just set one of these up in my home and your instructions were amazing in getting me up and running. I was just wondering if I could get your permission to include modified snippets of your code in my own repo if I make it publicly available. There's no licencing info in here so just wanted to get your express permission to use it - I'll make sure to add a link to this in my README :)

Thanks,
Ash

**Comment by charlottemach** [comment]
Sure, go ahead! I'm glad it's helping people :)
